"""
backend/services/speech_service.py

Server-side read-aloud for the treatment guidance.

Browsers only speak languages that have a voice installed on the device
(e.g. a typical Windows laptop has English voices only), so Tamil and
other Indian languages are synthesised with Gemini TTS instead.

Only guidance generated by this server is spoken - clients cannot send
arbitrary text, so the API key cannot be used as a free TTS service.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Sequence

from backend.prediction.confidence import LEVEL_UNCERTAIN
from backend.services.languages import LANGUAGES
from backend.services.llm import LLMNotConfiguredError, get_llm_provider
from backend.services.recommendation_service import LRUCache, generate_recommendation

logger = logging.getLogger(__name__)

# Audio is large (~48 KB per second); keep only a few results.
AUDIO_CACHE_SIZE = 16

_audio_cache = LRUCache(AUDIO_CACHE_SIZE)


def clear_cache() -> None:
    """Empty the audio cache (used by tests)."""

    _audio_cache.clear()


def build_speech_text(recommendation: Dict[str, Any]) -> str:
    """Plain spoken text from the structured guidance (no headings)."""

    g = recommendation["guidance"]
    parts: List[str] = [g["disease"], g["what_it_means"]]

    if recommendation["confidence_level"] == LEVEL_UNCERTAIN:
        parts.append(g["uncertainty_note"])

    for section in (
        "common_symptoms",
        "immediate_steps",
        "recommended_treatment",
        "preventive_measures",
        "when_to_seek_expert_help",
    ):
        parts.extend(g.get(section) or [])

    sentences = [p.strip().rstrip(".।") for p in parts if p and p.strip()]

    return ". ".join(sentences) + "."


def speak_guidance(
    predicted_class: str,
    level: str,
    alternatives: Sequence[str],
    language: str,
) -> Dict[str, Any]:
    """
    WAV audio of the guidance for a validated prediction.

    Raises:
        LLMError subclasses when guidance or speech generation fails.
    """

    provider = get_llm_provider()

    if not hasattr(provider, "synthesize_speech"):
        raise LLMNotConfiguredError("The configured LLM provider has no text-to-speech.")

    recommendation = generate_recommendation(
        predicted_class,
        level,
        alternatives,
        provider=provider,
        language=language,
    )

    text = build_speech_text(recommendation)
    key = (provider.name, getattr(provider, "tts_model", None), text)

    cached = _audio_cache.get(key)

    if cached is not None:
        return cached

    audio = provider.synthesize_speech(text, LANGUAGES[language][2])

    logger.info(
        "Synthesised %d chars of %s speech with %s (%.0f KB)",
        len(text),
        language,
        audio.model,
        len(audio.wav) / 1024,
    )

    result = {"wav": audio.wav, "model": audio.model, "characters": len(text)}
    _audio_cache.set(key, result)

    return result
